### ISSUE TITLE
TGA: dstOffset exception on some files

### ISSUE THREAD

**Issue by Krakean** [nickbabcock/Pfim#10]
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: dstOffset
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Pfim.Util.FillBottomLeft(Stream str, Byte[] data, Int32 rowSize, Int32 bufSize, Int32 padding) in d:\_GIT\Csharp-nices\Pfim\src\Pfim\Util.cs:line 128
   at Pfim.UncompressedTarga.BottomLeft(Stream str, TargaHeader header) in d:\_GIT\Csharp-nices\Pfim\src\Pfim\targa\UncompressedTarga.cs:line 18
   at Pfim.Targa.Create(Stream str) in d:\_GIT\Csharp-nices\Pfim\src\Pfim\targa\Targa.cs:line 45
   at Pfim.Pfim.FromFile(String path) in d:\_GIT\Csharp-nices\Pfim\src\Pfim\Pfim.cs:line 27

File: https://nofile.io/f/kksWGBcB8P3/TGA+File+Examples+4.rar

**Comment by Krakean** [comment]
All these tga files that were used in this and previous reports - displayed fine in either internal Total Commander file viewer, or in ImageGlass (also written in C#, available on github) or in Photoshop.

**Comment by nickbabcock** [comment]
Thank you for these reports! I'll look to start adding support for those tga files tonight!

**Comment by Krakean** [comment]
@nickbabcock 
Looking forward for fixes :)
I would like to use your dds/tga reader in my game engine, so had to test it on wide range of files, hopefully you don't mind about these reports :)

**Comment by nickbabcock** [comment]
Do you have qualms if I add the attached images as test cases?

**Comment by Krakean** [comment]
@nickbabcock 
No problem at all.
