### ISSUE TITLE
ArgumentOutOfRangeException in FromFile for DDS file

### ISSUE THREAD

**Issue by RunDevelopment** [nickbabcock/Pfim#82]
When using the following code:

```
var image = Pfim.Pfim.FromFile(file);
```

for the following file (see below) causes the following error to be thrown:

```
System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values.'
```

[image.zip](https://github.com/nickbabcock/Pfim/files/7707621/image.zip)

Full trace:

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values.
  Source=Pfim
  StackTrace:
   at Pfim.DdsHeaderDxt10.NewDecoder(DdsHeader header, PfimConfig config)
   at Pfim.Dds.DecodeDds(Stream stream, PfimConfig config, DdsHeader header)
   at Pfim.Dds.CreateSkipMagic(Stream stream, PfimConfig config)
   at Pfim.Pfim.FromStream(Stream stream, PfimConfig config)
   at Pfim.Pfim.FromFile(String path, PfimConfig config)
   at Pfim.Pfim.FromFile(String path)
   at DS3TexUpUI.DDSImage.Load(String file) in C:\Users\micha\source\repos\DS3TexUpUI\DS3TexUpUI\DDSConverter.cs:line 100
   at DS3TexUpUI.DDSConverter.ToPNG(String file, String targetDir) in C:\Users\micha\source\repos\DS3TexUpUI\DS3TexUpUI\DDSConverter.cs:line 20
   at DS3TexUpUI.Form1.button5_Click(Object sender, EventArgs e) in C:\Users\micha\source\repos\DS3TexUpUI\DS3TexUpUI\Form1.cs:line 175
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at DS3TexUpUI.Program.Main() in C:\Users\micha\source\repos\DS3TexUpUI\DS3TexUpUI\Program.cs:line 20

```

**Comment by nickbabcock** [comment]
Thank you for the report, this will be fixed shortly. The error message will also be improved.
